import { Profile, ProfilesCategory } from "payload-types";

export const initProfileCategories: ProfilesCategory[] = [
  {
    id: "1",
    name: "frontend",
    subcategory: "role",
    label: "Frontend dev",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "backend",
    subcategory: "role",
    label: "Backend dev",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "fullstack",
    subcategory: "role",
    label: "Fullstack dev",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "mobile",
    subcategory: "role",
    label: "Mobile dev",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "game",
    subcategory: "role",
    label: "Game dev",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "react",
    subcategory: "technology",
    label: "React",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "vue",
    subcategory: "technology",
    label: "Vue.js",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "react-native",
    subcategory: "technology",
    label: "React Native",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "11",
    name: "angular",
    subcategory: "technology",
    label: "Angular",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "ember",
    subcategory: "technology",
    label: "Ember",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "13",
    name: "nextjs",
    subcategory: "technology",
    label: "NextJS",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "14",
    name: "svelte",
    subcategory: "technology",
    label: "Svelte",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "15",
    name: "gatsby",
    subcategory: "technology",
    label: "Gatsby",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "16",
    name: "nuxtjs",
    subcategory: "technology",
    label: "NuxtJS",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "17",
    name: "node",
    subcategory: "technology",
    label: "Node",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "18",
    name: "fastify",
    subcategory: "technology",
    label: "Fastify",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "19",
    name: "nestjs",
    subcategory: "technology",
    label: "NestJS",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "20",
    name: "graphql",
    subcategory: "technology",
    label: "GraphQL",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "21",
    name: "aws",
    subcategory: "technology",
    label: "AWS",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "22",
    name: "javascript",
    subcategory: "technology",
    label: "Javascript",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "23",
    name: "css",
    subcategory: "technology",
    label: "CSS",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "24",
    name: "html",
    subcategory: "technology",
    label: "HTML",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "25",
    name: "chrome-extension",
    subcategory: "technology",
    label: "Chrome extensions",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "26",
    name: "meteor",
    subcategory: "technology",
    label: "Meteor",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "27",
    name: "git",
    subcategory: "technology",
    label: "Git",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "28",
    name: "saas",
    subcategory: "technology",
    label: "Saas",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "29",
    name: "amazon-s3",
    subcategory: "technology",
    label: "Amazon S3",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "30",
    name: "solidity",
    subcategory: "technology",
    label: "Solidity",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "31",
    name: "web3",
    subcategory: "technology",
    label: "Web3",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "32",
    name: "typescript",
    subcategory: "technology",
    label: "TypeScript",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "33",
    name: "express",
    subcategory: "technology",
    label: "Express.js",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "34",
    subcategory: "openTo",
    name: "remote",
    label: "Remote",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "35",
    subcategory: "openTo",
    name: "onsite",
    label: "On-site",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "36",
    subcategory: "openTo",
    name: "hybrid",
    label: "Hybrid",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "37",
    subcategory: "timeCapacity",
    name: "full-time",
    label: "Full-time",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "38",
    subcategory: "timeCapacity",
    name: "part-time",
    label: "Part-time",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
  {
    id: "39",
    subcategory: "timeCapacity",
    name: "contract",
    label: "Contract",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  },
];

export const initProfiles: Profile[] = ([] = [
  {
    id: "aaa",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    description:
      "Full-stack developer with 5 years of experience. Passionate about React and Node.js.",
  },
  {
    id: "bbb",
    updatedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    description:
      "Passionate full-stack developer with 7+ years of experience. Specializing in JavaScript ecosystems, particularly React and Node.js. Always eager to tackle new challenges and contribute to innovative projects. In my free time, I enjoy contributing to open-source and mentoring aspiring developers.",
  },
]);
